CREATE OR REPLACE PROCEDURE PRC_CORRIGIR_PCCLIENT_CAMPOS (
  p_total_lidos OUT NUMBER,
  p_total_corrigidos OUT NUMBER
) AS
BEGIN
  SELECT COUNT(1)
    INTO p_total_lidos
    FROM PCCLIENT P
   WHERE P.DTEXCLUSAO IS NULL;

  MERGE INTO PCCLIENT P
  USING (
    SELECT
      P.CODCLI,
      CASE
        WHEN P.CODREDE IN (1, 6, 11) THEN 'DIAMANTE'
        WHEN P.CODREDE IN (2, 7, 12) THEN 'PLATINUM'
        WHEN P.CODREDE IN (3, 8, 13) THEN 'OURO'
        WHEN P.CODREDE IN (4, 9, 14) THEN 'PRATA'
        WHEN P.CODREDE IN (5, 10, 15) THEN 'BRONZE'
        ELSE NULL
      END AS CATEGORIA_CORRIGIDA
    FROM PCCLIENT P
    WHERE P.DTEXCLUSAO IS NULL
  ) SRC
    ON (P.CODCLI = SRC.CODCLI)
  WHEN MATCHED THEN UPDATE SET
    P.CATEGORIA = SRC.CATEGORIA_CORRIGIDA
  WHERE SRC.CATEGORIA_CORRIGIDA IS NOT NULL
    AND NVL(UPPER(TRIM(P.CATEGORIA)), '#') <> NVL(SRC.CATEGORIA_CORRIGIDA, '#');

  p_total_corrigidos := SQL%ROWCOUNT;
END;
/
